name: release
description: ''

inputs:
  github_token:
    description: ''
    required: true
  dockerhub_username:
    description: ''
    required: true
  dockerhub_token:
    description: ''
    required: true
  ref_name:
    description: ''
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Copy all binaries'
    shell: sh
    run: |
      container_id=$(docker create --pull always vladimirdev635/gql-targets:${{ inputs.ref_name }} sh)
      docker cp $container_id:/targets ./cli-targets
      docker rm $container_id

      container_id=$(docker create --pull always vladimirdev635/gql-treesitter-targets:${{ inputs.ref_name }} sh)
      docker cp $container_id:/ ./treesitter
      docker rm $container_id

      mkdir linux-x86_64
      mkdir linux-arm64
      mkdir darwin-x86_64
      mkdir darwin-arm64

      mv ./cli-targets/x86_64-darwin ./darwin-x86_64/cli
      mv ./treesitter/targets/x86_64-darwin ./darwin-x86_64/treesitter
      cp ./treesitter/queries ./darwin-x86_64/treesitter/queries

      mv ./cli-targets/arm64-darwin ./darwin-arm64/cli
      mv ./treesitter/targets/arm64-darwin ./darwin-arm64/treesitter
      cp ./treesitter/queries ./darwin-arm64/treesitter/queries

      mv ./cli-targets/arm64-linux ./linux-arm64/cli
      mv ./treesitter/targets/arm64-linux ./linux-arm64/treesitter
      cp ./treesitter/queries ./linux-arm64/treesitter/queries

      mv ./cli-targets/x86_64-linux ./linux-x86_64/cli
      mv ./treesitter/targets/x86_64-linux ./linux-x86_64/treesitter
      cp ./treesitter/queries ./linux-x86_64/treesitter/queries

      ls ./
      ls ./darwin-x86_64
      ls ./darwin-x86_64/treesitter
  #- uses: "marvinpinto/action-automatic-releases@latest"
  #  with:
  #    repo_token: "${{ inputs.github_token }}"
  #    title: "Release ${{ inputs.ref_name }}"
  #    prerelease: false
  #    files: |
  #      gql-linux-x86_64.tar.gz
  #      gql-linux-arm64.tar.gz
  #      gql-darwin-x86_64.tar.gz
  #      gql-darwin-arm64.tar.gz
