services:
  graphql:
    build:
      context: ./graphql
      args:
        BASE_IMAGE: ${GRAPHQL_BASE_IMAGE}
    command: ['echo', 'something']
  rust-server:
    depends_on:
      graphql:
        condition: service_completed_successfully
    image: ${RUST_SERVER_IMAGE}
    environment:
      PORT: '8000'
  typescript-client:
    stop_grace_period: 0s
    depends_on:
      graphql:
        condition: service_completed_successfully
    image: ${TYPESCRIPT_CLIENT_IMAGE}
    command: ['sleep', 'infinity']
    environment:
      ENDPOINT_URL: http://rust-server:8000/graphql
