name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install clang"
      run: sudo apt update && sudo apt-get install --no-install-recommends -y libc++-18-dev clang-18
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        args: -DCMAKE_CXX_FLAGS='-D__cpp_concepts=202002L'
        run-build: true
        c-compiler: clang-18
        cxx-compiler: clang++-18
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
