name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache LLVM Build
      id: cache-llvm-build
      uses: actions/cache@v4
      with:
        path: ./scripts/llvm/build/
        key: ${{ runner.os }}-llvm-build
    - name: Install llvm
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: sh ./scripts/build-llvm-from-source.sh
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      env:
        CC: ./scripts/llvm/build/bin/clang
        CXX: ./scripts/llvm/build/bin/clang++
      with:
        run-build: true
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
