name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install clang"
      run: sudo apt update && sudo apt-get install --no-install-recommends -y libc++-18-dev clang-18 build-essential
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      env:
        CC: clang-18
        CXX: clang++-18
      with:
        args: -DCMAKE_CXX_COMPILER_FORCED=1 -DCMAKE_C_COMPILER_FORCED=1
        run-build: true
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
