name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install clang"
      run: sudo apt update && sudo apt-get install --no-install-recommends -y libc++-18-dev clang-18
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        args: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-D__cpp_concepts=202002L' -DCMAKE_EXE_LINKER_FLAGS='-static'
        run-build: true
        c-compiler: clang-18
        cxx-compiler: clang++-18
    - name: Run tests
      working-directory: ./build
      run: ctest .
    - name: Run on quickclick schema
      run: ./build/gql internal parse-dir --client-dir './check/client' --server-dir './check/server' > schema.json
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
  build-completions:
    name: Build bash completions
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install completely"
      run: sudo apt update && sudo apt-get install -y rubygems-integration && sudo gem install completely
    - name: "Build completions"
      run: cd autocomplete && completely generate
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli-completions'
        path: autocomplete/completely.bash
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
