name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libc++-18-dev clang-18
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        args: -DCMAKE_CXX_FLAGS="-fexperimental-library" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        run-build: true
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
