name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libc++-18-dev clang-18
    - name: Cache Build
      id: restore-cache-build
      uses: actions/cache/restore@v4
      with:
        path: c++/gql/build
        key: ${{ runner.os }}-build
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        source-dir: c++/gql
        args: -DCMAKE_BUILD_TYPE=Release -DGQL_BUILD_TESTS=true -DCMAKE_CXX_FLAGS='-D__cpp_concepts=202002L' -DCMAKE_EXE_LINKER_FLAGS='-static'
        build-args: --parallel 4
        run-build: true
        c-compiler: clang-18
        cxx-compiler: clang++-18
    - uses: actions/cache/save@v3
      name: Save build cache
      with:
        path: c++/gql/build
        key: ${{ runner.os }}-build
    - name: Run tests
      working-directory: ./c++/gql/build
      run: ctest --rerun-failed --output-on-failure .
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: c++/gql/build/bin/gql
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref_type == 'tag'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Release ${{ github.ref_name }}"
        prerelease: false
        files: |
          c++/gql/build/bin/gql
  build-completions:
    name: Build bash completions
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install completely"
      run: sudo apt update && sudo apt-get install -y rubygems-integration && sudo gem install completely
    - name: "Build completions"
      working-directory: c++/gql
      run: cd autocomplete && completely generate
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli-completions'
        path: c++/gql/autocomplete/completely.bash
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
