name: "c++ gql build"

on:
  push:
    paths:
      - cpp/gql/**
      - .github/workflows/cpp-gql.yaml
      - shared/dockerfiles/gql
      - shared/dockerfiles/gql.dockerignore
      - shared/dockerfiles/gql-darwin
      - shared/dockerfiles/gql-darwin.dockerignore

jobs:
  docker:
      runs-on: ubuntu-latest
      environment: cpp-gql
      needs:
        - build
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: awalsh128/cache-apt-pkgs-action@latest
          with:
            packages: zip
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            file: shared/dockerfiles/gql
            push: true
            target: scratch
            platforms: linux/amd64,linux/arm64
            tags: vladimirdev635/gql:${{ github.ref_name }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            file: shared/dockerfiles/gql
            push: true
            target: alpine
            platforms: linux/amd64,linux/arm64
            tags: vladimirdev635/gql:alpine-${{ github.ref_name }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            file: shared/dockerfiles/gql-darwin
            push: true
            platforms: linux/amd64,linux/arm64
            tags: vladimirdev635/gql-darwin:${{ github.ref_name }}
        - name: 'Copy all binaries'
          run: |
            container_id=$(docker create vladimirdev635/gql-darwin:${{ github.ref_name }} --platform=linux/amd64)
            docker cp $container_id:/gql ./gql-darwin-x86_64
            tar -cvzf ./gql-darwin-x86_64.tar.gz ./gql-darwin-x86_64
            zip ./gql-darwin-x86_64.zip ./gql-darwin-x86_64
            docker rm $container_id
            container_id=$(docker create vladimirdev635/gql-darwin:${{ github.ref_name }} --platform=linux/arm64)
            docker cp $container_id:/gql ./gql-darwin-arm64
            tar -cvzf ./gql-darwin-arm64.tar.gz ./gql-darwin-arm64
            zip ./gql-darwin-arm64.zip ./gql-darwin-arm64
            docker rm $container_id
            container_id=$(docker create vladimirdev635/gql:${{ github.ref_name }} --platform=linux/amd64)
            docker cp $container_id:/gql ./gql-linux-x86_64
            tar -cvzf ./gql-linux-x86_64.tar.gz ./gql-linux-x86_64
            zip ./gql-linux-x86_64.zip ./gql-linux-x86_64
            docker rm $container_id
            container_id=$(docker create vladimirdev635/gql:${{ github.ref_name }} --platform=linux/arm64)
            docker cp $container_id:/gql ./gql-linux-arm64
            tar -cvzf ./gql-linux-arm64.tar.gz ./gql-linux-arm64
            zip ./gql-linux-arm64.zip ./gql-linux-arm64
            docker rm $container_id
            ls
        - uses: "marvinpinto/action-automatic-releases@latest"
          if: github.ref_type == 'tag'
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            title: "Release ${{ github.ref_name }}"
            prerelease: false
            files: |
              gql-linux-x86_64.tar.gz
              gql-linux-x86_64.zip
              gql-linux-arm64.tar.gz
              gql-linux-arm64.zip
              gql-darwin-x86_64.tar.gz
              gql-darwin-x86_64.zip
              gql-darwin-arm64.tar.gz
              gql-darwin-arm64.zip
