name: "e2e-tests"

on:
  push:
    paths:
    - e2e-tests/**
    - shared/dockerfiles/e2e-tests/**
    - .github/workflows/e2e-tests.yaml
  workflow_run:
    workflows:
    - "rust cli build"
    - "rust-gqlcodegen"
    - "rust-libgql"
    - "typescript gql-codegen"
    - "typescript gql-client"
    types: 
    - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GRAPHQL_BASE_IMAGE: vladimirdev635/gql-alpine:${{ github.ref_name }}
      COMPOSE_FILE: ./e2e-tests/docker-compose.yaml
      RUST_SERVER_IMAGE: vladimirdev635/e2e-tests-rust-server:${{ github.ref_name }}
      TYPESCRIPT_CLIENT_IMAGE: vladimirdev635/e2e-tests-typescript-client:${{ github.ref_name }}
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build e2e-tests rust-server
      uses: docker/build-push-action@v6
      with:
        file: shared/dockerfiles/e2e-tests/rust-server
        push: true
        target: targets
        tags: vladimirdev635/e2e-tests-rust-server:${{ github.ref_name }}
        cache-from: type=registry,ref=vladimirdev635/e2e-tests-rust-server:buildcache
        cache-to: type=registry,ref=vladimirdev635/e2e-tests-rust-server:buildcache,mode=max
        provenance: false
        sbom: false
    - name: Build e2e-tests typescript-client
      uses: docker/build-push-action@v6
      with:
        file: shared/dockerfiles/e2e-tests/typescript-client
        push: true
        target: targets
        tags: vladimirdev635/e2e-tests-typescript-client:${{ github.ref_name }}
        cache-from: type=registry,ref=vladimirdev635/e2e-tests-typescript-client:buildcache
        cache-to: type=registry,ref=vladimirdev635/e2e-tests-typescript-client:buildcache,mode=max
        provenance: false
        sbom: false
    - name: Docker compose up
      run: docker compose up -d
    - name: Run typescript-client tests
      run: docker compose exec typescript-client bun start
    - name: Docker compose down
      if: always()
      run: docker compose down
